export const READ_PORTFOLIO = 'READ_PORTFOLIO';
export const READ_PORTFOLIO_FAILED = 'READ_PORTFOLIO_FAILED';
export const READ_PORTFOLIO_SUCCESS = 'READ_PORTFOLIO_SUCCESS';

export const CREATE_PORTFOLIO = 'CREATE_PORTFOLIO';
export const CREATE_PORTFOLIO_FAILED = 'CREATE_PORTFOLIO_FAILED';
export const CREATE_PORTFOLIO_SUCCESS = 'CREATE_PORTFOLIO_SUCCESS';

export const UPDATE_PORTFOLIO = 'UPDATE_PORTFOLIO';
export const UPDATE_PORTFOLIO_FAILED = 'UPDATE_PORTFOLIO_FAILED';
export const UPDATE_PORTFOLIO_SUCCESS = 'UPDATE_PORTFOLIO_SUCCESS';

export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO';
export const DELETE_PORTFOLIO_FAILED = 'DELETE_PORTFOLIO_FAILED';
export const DELETE_PORTFOLIO_SUCCESS = 'DELETE_PORTFOLIO_SUCCESS';