export const READ_RESUME = 'READ_RESUME';
export const READ_RESUME_FAILED = 'READ_RESUME_FAILED';
export const READ_RESUME_SUCCESS = 'READ_RESUME_SUCCESS';

export const CREATE_RESUME = 'CREATE_RESUME';
export const CREATE_RESUME_FAILED = 'CREATE_RESUME_FAILED';
export const CREATE_RESUME_SUCCESS = 'CREATE_RESUME_SUCCESS';

export const UPDATE_RESUME = 'UPDATE_RESUME';
export const UPDATE_RESUME_FAILED = 'UPDATE_RESUME_FAILED';
export const UPDATE_RESUME_SUCCESS = 'UPDATE_RESUME_SUCCESS';

export const DELETE_RESUME = 'DELETE_RESUME';
export const DELETE_RESUME_FAILED = 'DELETE_RESUME_FAILED';
export const DELETE_RESUME_SUCCESS = 'DELETE_RESUME_SUCCESS';