export const READ_INITIAL_INFORMATION = 'READ_INITIAL_INFORMATION';
export const READ_INITIAL_INFORMATION_FAILED = 'READ_INITIAL_INFORMATION_FAILED';
export const READ_INITIAL_INFORMATION_SUCCESS = 'READ_INITIAL_INFORMATION_SUCCESS';