export const READ_KNOWLEDGE = 'READ_KNOWLEDGE';
export const READ_KNOWLEDGE_FAILED = 'READ_KNOWLEDGE_FAILED';
export const READ_KNOWLEDGE_SUCCESS = 'READ_KNOWLEDGE_SUCCESS';

export const CREATE_KNOWLEDGE = 'CREATE_KNOWLEDGE';
export const CREATE_KNOWLEDGE_FAILED = 'CREATE_KNOWLEDGE_FAILED';
export const CREATE_KNOWLEDGE_SUCCESS = 'CREATE_KNOWLEDGE_SUCCESS';

export const UPDATE_KNOWLEDGE = 'UPDATE_KNOWLEDGE';
export const UPDATE_KNOWLEDGE_FAILED = 'UPDATE_KNOWLEDGE_FAILED';
export const UPDATE_KNOWLEDGE_SUCCESS = 'UPDATE_KNOWLEDGE_SUCCESS';

export const DELETE_KNOWLEDGE = 'DELETE_KNOWLEDGE';
export const DELETE_KNOWLEDGE_FAILED = 'DELETE_KNOWLEDGE_FAILED';
export const DELETE_KNOWLEDGE_SUCCESS = 'DELETE_KNOWLEDGE_SUCCESS';